[build]
  base = "frontend"             # Base directory where your frontend code is located
  command = "npm run build"     # Command to build your project
  publish = "build"             # Directory to publish the build output

[build.environment]
  CI = "false"  # Optional: Set to false to avoid treating warnings as errors
